[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "anttsmartbot"
version = "1.0.0"
authors = [
  { name = "Fernando Xavier de Castro", email = "ferdxavier@gmail.com" }
]